/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Minas.ValidadorTablero;
import Minas.Minas;
import java.awt.Dimension;
import java.awt.event.ActionListener;
import javax.swing.JPanel;

/**
 *
 * @author Noemi Guzman
 */
public class TableroPanel extends javax.swing.JPanel {
    Minas miJuego;
    ValidadorTablero validador;
    int casillasJugadas;
    boolean terminoJuego;
    int anchoTablero;
    int altoTablero;
    int nBombas;   
    private JPanel panel;

    /**
     * Creates new form TableroPanel
     */
    public TableroPanel() {
        initComponents();
        
    }

    TableroPanel(int alturaT, int anchoT, int nBombasT) {
        anchoTablero=anchoT;
        altoTablero=alturaT;
        nBombas=nBombasT;
        System.out.println("Crear Tablero: Alto "+ String.valueOf(alturaT) + " anchos " +String.valueOf(anchoT) + " Bombas " + String.valueOf(nBombasT)   ); 
        panel = new JPanel();
        
        miJuego= new Minas(alturaT,anchoT);
        miJuego.cargarUnNumeroDeBombas(nBombas);
        panel.setPreferredSize(new Dimension(220, 40));
        setPanelTablero();
        mapearTablero();    
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    private void mapearTablero(){        
        for (int fila = 0; fila < altoTablero; fila++) {
            for (int col = 0; col < anchoTablero; col++) {    
                Casilla temp = new Casilla(fila,col);    
                temp.setValor(miJuego.abrirJugada(fila, col));        
                //temp.addActionListener((ActionListener) this);
                this.add(temp);                                
            }
        }
        this.setVisible(true);
    }
    
    private void mostarTableroCompleto(){
        this.repaint();
        setPanelTablero();
        System.out.println("cargando el tablero completo"  );    
        for (int fila = 0; fila < altoTablero; fila++) {
            for (int col = 0; col < anchoTablero; col++) {
                Casilla temp = new Casilla(fila,col);                
                temp.setValor(miJuego.abrirJugada(fila,col ));
                temp.addActionListener((ActionListener) this);       
                temp.mostrarJugador();
                this.add(temp);                             
            }
        }
        this.validate();
        this.setVisible(true);
    }
    private void setPanelTablero(){
        this.removeAll();           
        this.setLayout(new java.awt.GridLayout(altoTablero, anchoTablero));
    }
}
